# Configuration for "Your Workflow Name" action
# Copy to: `.github/maintenance-actions/your-workflow-config.yml`
# Customize for your project

# ==============================================================================
# Project board configuration
# ==============================================================================
projectBoard:
  defaultStatus: "QA"  # Issues with this status are checked
  doneStatus: "Done"   # Issues with this status are not checked

# ==============================================================================
# Label Directory
# ==============================================================================
# This workflow uses issue labels to:
#   1. Flag issues that need updates from the assignee, and
#   2. Exclude issues that do not need to be checked.
#
# The workflow relies on 'label keys' to identify the purpose of each label. These
# 'label keys' correspond to the actual 'label names' (i.e. `Complexity: Medium`, 
# `role: front end`, etc.) for the label. The `label-directory.yml` file defines 
# the key-value pair mapping between 'label keys' and 'Label Name' values:
# 
#   labelKey1: "Label Name 1"
#   labelKey2: "Label Name 2"
#
# The path to your project's label directory file (relative to the project root) 
# is defined below. The workflow uses this file to correlate label keys with 
# the actual labels in your repository.

labelDirectoryPath: ".github/maintenance-actions/label-directory.yml"

# The 'label keys' are used internally and should not be changed. Since, however, 
# each project might name issue labels differently, this workflow allows you to 
# customize the 'label name' values to match your project's actual issue labels.
# Note especially the next section. 



# ==============================================================================
# Labels used by this workflow
# ==============================================================================
# The following 'label keys' must be mapped to your project's actual 'label names' 
# via the `label-directory.yml` file. These labels are used by the workflow to 
# determine whether a completed issue should be sorted with "QA" or with "Done" 
# status. If you use different status names in your Project Board, change them 
# below to match your Project Board status names.
labels:
  # Hard labels (optional) are sorted to "Done" status. You may add or remove label 
  # keys to this list as needed.

  hardLabels:
    - featureRefactorCss
    - featureRefactorHtml
    - featureRefactorJsLiquid
    - featureRefactorGha

  # Soft labels (optional) are sorted to "Done" status. You may add or remove label
  # keys to this list as needed.

  softLabels:
    - roleBackEndDevOps
    - featureAnalytics

  # Override labels (optional) are sorted to "QA" status. You may add or remove label 
  # keys to this list as needed.

  overrideLabels:
    - roleFrontEnd

  # Note that if an issue has none of the above labels, it will be sorted to "QA" 
  # status by default.



# ==============================================================================
# Advanced options
# ==============================================================================
# dryRun: false  # Set to true to preview changes without applying them