name: Move Closed Issues
on:
  issues:
    types:
      - closed

# Default token permissions
permissions:
  contents: read
  issues: read

jobs:
  Move-Closed-Issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: hackforla/maintenance-actions/move-closed-issues@v1
        with:
          github-token: ${{ secrets.PROJECT_GRAPHQL_TOKEN }}   # CUSTOMIZE: Change to your project secret / token

