name: Add Update Label Weekly
# aka "Schedule Friday 0700"
description: Monitors “In Progress” issues for recent updates since the last run and posts reminders to assignees who haven’t provided activity. 
author: Hack for LA

inputs:
  github-token:
    description: 'GitHub token with repo and project scopes'
    required: true
  config-path:
    description: 'Path to YAML config file in the calling repo'
    required: false
    default: '.github/maintenance-actions/add-update-label-config.yml'
  
  # Optional overrides (if not using config file)
  updated-by-days:
    description: 'Days within which issue is considered current'
    required: false
  comment-by-days:
    description: 'Days before first warning label'
    required: false
  inactive-by-days:
    description: 'Days before inactive label'
    required: false
  target-status:
    description: 'Project board status to check'
    required: false
  statusUpdated:
    description: 'Label keyName for "Status: Updated"'
    required: false
  statusInactive1:
    description: 'Label keyName for "To Update!"'  
    required: false
  statusInactive2:
    description: 'Label keyName for "2 weeks inactive"'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout maintenance-actions
      uses: actions/checkout@v5
      with:
        repository: ${{ github.repository_owner }}/maintenance-actions
        path: .maintenance-actions
        
    - name: Checkout calling repository
      uses: actions/checkout@v5
      with:
        path: .project-repo
    
    - name: Add update labels to applicable issues
      uses: actions/github-script@v8
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const path = require('path');
          const fs = require('fs');
          
          // Set working directory paths
          const maintenanceActionsPath = path.join(process.cwd(), '.maintenance-actions');
          process.chdir(maintenanceActionsPath);
          
          // Set environment variables for index.js to use
          process.env.PROJECT_REPO_PATH = path.join(process.cwd(), '../.project-repo');
          process.env.CONFIG_PATH = '${{ inputs.config-path }}';
          process.env.OVERRIDE_UPDATED_BY_DAYS = '${{ inputs.updated-by-days }}';
          process.env.OVERRIDE_COMMENT_BY_DAYS = '${{ inputs.comment-by-days }}';
          process.env.OVERRIDE_INACTIVE_BY_DAYS = '${{ inputs.inactive-by-days }}';
          process.env.OVERRIDE_TARGET_STATUS = '${{ inputs.target-status }}';
          process.env.OVERRIDE_LABEL_STATUS_UPDATED = '${{ inputs.label-status-updated }}';
          process.env.OVERRIDE_LABEL_STATUS_INACTIVE1 = '${{ inputs.label-status-inactive1 }}';
          process.env.OVERRIDE_LABEL_STATUS_INACTIVE2 = '${{ inputs.label-status-inactive2 }}';
          
          // Load and run the index.js module
          const runAction = require('./add-update-label-weekly/index.js');
          await runAction({ github, context });
          
branding:
  icon: 'clock'
  color: 'blue'
