name: Add Update Label Weekly
# aka "Schedule Friday 0700"
description: Automatically manages issue label update reminders based on assignee activity 
author: Hack for LA

inputs:
  github-token:
    description: 'GitHub token with repo and project scopes'
    required: true
  config-path:
    description: 'Path to YAML config file in the calling repo'
    required: false
    default: '.github/maintenance-actions/add-update-label-config.yml'
  
  # Optional overrides (if not using config file)
  updated-by-days:
    description: 'Days within which issue is considered current'
    required: false
  comment-by-days:
    description: 'Days before first warning label'
    required: false
  inactive-updated-by-days:
    description: 'Days before inactive label'
    required: false
  target-status:
    description: 'Project board status to check'
    required: false
  statusUpdated:
    description: 'Label keyName for "Status: Updated"'
    required: false
  statusInactive1:
    description: 'Label keyName for "To Update!"'  
    required: false
  statusInactive2:
    description: 'Label keyName for "2 weeks inactive"'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout maintenance-actions
      uses: actions/checkout@v5
      with:
        repository: ${{ github.repository_owner }}/maintenance-actions
        path: .maintenance-actions
        
    - name: Checkout calling repository
      uses: actions/checkout@v5
      with:
        path: .project-repo
    
    - name: Add update labels to applicable issues
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const path = require('path');
          const fs = require('fs');
          
          // Set working directory paths
          const maintenanceActionsPath = path.join(process.cwd(), '.maintenance-actions');
          const projectRepoPath = path.join(process.cwd(), '.project-repo');
          
          // Load configuration
          const loadStalenessConfig = require(path.join(maintenanceActionsPath, 'core/staleness/config.js'));
          
          const overrides = {
            updatedByDays: '${{ inputs.updated-by-days }}' || undefined,
            commentByDays: '${{ inputs.comment-by-days }}' || undefined,
            inactiveUpdatedByDays: '${{ inputs.inactive-updated-by-days }}' || undefined,
            targetStatus: '${{ inputs.target-status }}' || undefined,
            labelStatusUpdated: '${{ inputs.label-status-updated }}' || undefined,
            labelStatusInactive1: '${{ inputs.label-status-inactive1 }}' || undefined,
            labelStatusInactive2: '${{ inputs.label-status-inactive2 }}' || undefined,
          };
          
          const config = loadStalenessConfig({
            projectRepoPath,
            configPath: '${{ inputs.config-path }}',
            overrides,
          });
          
          // Load and run main script
          const addLabelMain = require(path.join(maintenanceActionsPath, 'core/staleness/add-label.js'));
          await addLabelMain({ g: github, c: context, config, projectRepoPath });
          
branding:
  icon: 'clock'
  color: 'blue'
