name: 'Add Update Label Weekly'
description: 'Checks issue staleness and applies appropriate labels based on last update time'
author: 'Your Organization'

inputs:
  github-token:
    description: 'GitHub token with permissions to read issues and manage labels'
    required: true
  config-path:
    description: 'Path to the configuration file relative to repository root'
    required: false
    default: '.github/maintenance-actions/add-update-label-config.yml'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'clock'
  color: 'blue'