name: 'Add Update Label Weekly'
description: 'Monitors “In Progress” issues for recent updates and posts reminders to assignees who have not provided activity.'
author: 'Hack for LA'

inputs:
  github-token:
    description: 'GitHub PAT with scopes `repo (full)` and `project (full)`'
    required: true
  config-path:
    description: 'Path to the configuration file relative to repository root'
    required: false
    default: '.github/maintenance-actions/add-update-label-config.yml'
  dry-run:
    description: 'Run in dry-run mode without posting comments or updating issues'
    required: true
    default: 'false'
    

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'clock'
  color: 'blue'
